# The maximum duration of files to save in seconds.
# Acceptable values: positive integers
# If not given defaults to 300 seconds
# If invalid value is given node will exit and log an error message
# max_record_time:
