name: 'ros1-integ-test'
description: 'Run rostest based integration tests for ROS1 packages'
inputs:
  ros-distro:
    description: 'Distribution of ROS you are using [kinetic|melodic]'
    required: true
  integ-test-package-name:
    description: 'Name of the integration test package'
    required: true
  integ-test-launch-files:
    description: 'Name of the integration test launch files, newline separated'
    required: true
  workspace-dir:
    description: 'Path to the workspace folder that contains your package/s'
    default: './'
runs:
  using: 'node12'
  main: 'dist/index.js'
