name: 'ros1-ci'
description: 'Build and Test your ROS1 Package'
inputs:
  workspace-dir:
    description: 'Path to the workspace folder of your package'
    default: './'
  ros-distro:
    description: 'Distribution of ROS you are using [kinetic|melodic]'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'