#Goal
# Upload destination. No validity checks are done at the time of acceptance
string destination
----
#Result
RecorderResult result
----
#Feedback
# This is system time
time started
RecorderStatus status
