name: Build & Test release-latest
on:
  schedule:
    # Run every hour. This helps detect flakiness,
    # and broken external dependencies.
    - cron:  '0 * * * *'

jobs:
  build_and_test_release_latest:
    name: Build and Test Release Latest ROS ${{ matrix.ros_version }} ${{ matrix.ros_distro }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ros_distro: [kinetic, melodic]
        include:
        - ros_distro: kinetic
          ubuntu_distro: xenial
        - ros_distro: melodic
          ubuntu_distro: bionic
    container:
      image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu_distro }}-ros-${{ matrix.ros_distro }}-ros-base-latest
    env:
      # Needed for the CMakeLists.txt setup
      ROS_DISTRO: ${{ matrix.ros_distro }}
      ROS_VERSION: 1
    steps:
    # TODO(setup-ros-docker#7): calling chown is necessary for now
    - name: Run setup-ros-docker workaround
      run: sudo chown -R rosbuild:rosbuild "$HOME" .
    # Needed to access the vcs repos file from the workspace
    - name: Checkout source
      uses: actions/checkout@v2
    - name: Run action-ros-ci to build and test
      uses: ros-tooling/action-ros-ci@0.0.17
      with:
        source-ros-binary-installation: ${{ matrix.ros_distro }}
        package-name: file_uploader_msgs rosbag_cloud_recorders recorder_msgs rosbag_uploader_ros1_integration_tests s3_common s3_file_uploader
        # schedule runs against the default branch (master), so specify release-latest via repos file
        vcs-repo-file-url: "${{ github.workspace }}/.github/workflows/release_latest.repos"
    - name: Upload resulting colcon logs
      uses: actions/upload-artifact@v1
      with:
        name: colcon-logs-${{ matrix.ubuntu_distro }}-ros-${{ matrix.ros_distro }}
        path: ros_ws/log
