name: "Lint rosbag-uploader-ros1"
on:
  pull_request:

jobs:
  ament_lint:
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-bionic-ros-eloquent-ros-base-latest
    strategy:
      fail-fast: false
      matrix:
        linter: [copyright, cppcheck, cpplint, flake8, pep257, uncrustify, xmllint]
    steps:
      - run: sudo chown -R rosbuild:rosbuild "$HOME" .
      - uses: actions/checkout@v2
      - uses: ros-tooling/action-ros-lint@0.0.6
        with:
          distribution: eloquent
          linter: ${{ matrix.linter }}
          package-name: |
            rosbag_cloud_recorders
            rosbag_uploader_ros1_integration_tests
            s3_common s3_file_uploader
